runtime: python
api_version: '1'
env: flexible
threadsafe: false
handlers:
- url: /.*
  script: main.app
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
network:
  instance_tag: websocket
  forwarded_ports:
    - '65080'
entrypoint: gunicorn -k eventlet -w 1 -b :$PORT wsgi