runtime: python
api_version: 1
threadsafe: false
env: flex

handlers:
- url: /.*
  script: main.app

network:
  forwarded_ports:
  - 65080
  instance_tag: websocket

entrypoint: gunicorn -k eventlet -w 1 -b :$PORT wsgi